### ISSUE TITLE
[求助] 在旁路由时 ip 转发无法正常工作

### ISSUE THREAD

**Issue by alongw** [juewuy/ShellCrash#531]
### Verify steps

-  我已经在 [Issue Tracker](https://github.com/juewuy/ShellCrash/issues/……/) 中找过我要提出的问题 I have searched on the [issue tracker](https://github.com/juewuy/ShellCrash/issues/……/) for a related issue.
-  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists.
-  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题

### Description

本人知道该问题应该与此仓库软件无关，但是经过探究和寻找无法解决，因此仍决定开启该 issue

在旁路由时 ip 转发无法正常工作

旁路由信息如下

系统：Ubuntu 22.04
ip：10.0.0.200/**24**
主路由：10.0.0.101

根据教程正确安装和配置 clash ，使用 最新 meta 内核 （2023-11-25 `5f7053c5` 虚空终端），部分文件（安装目录下 `config.yaml` 即 `./yamls/config.yaml`）如下

```
mixed-port: 11451
redir-port: 7891
tproxy-port: 1536

allow-lan: true
geodata-mode: true
unified-delay: true
find-process-mode: strict
mode: rule

secret: "***"
external-ui: ./ui
external-controller: 0.0.0.0:9090
external-controller-tls: 0.0.0.0:9091
enable-process: true
tls:
  certificate: ./tls/cer
  private-key: ./tls/key

log-level: info
ipv6: false
tcp-concurrent: true
global-client-fingerprint: firefox
keep-alive-interval: 15

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  ipv6: true
  ipv6-timeout: 300
  default-nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.1#PROXY
    - 8.8.8.8#PROXY
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  nameserver-policy:
    "geosite:cn":
      - https://223.5.5.5/dns-query
      - https://223.6.6.6/dns-query
```

测试机直接使用局域网内设置使用 socks5 连接，配置地址 `10.0.0.200` 端口 `11451` 可正常科学上网

根据常见问题以及其他 issue 中的内容，关闭测试机 ipv6 ，在旁路由中开启 ip 转发，并重启相关功能（确保 ip 转发仍然生效）

根据常见问题以及其他 issue 中的内容，临时关闭旁路由系统防火墙

修改测试机 IP 信息 ，IP `10.0.0.85` 子网掩码 `255.255.255.0` 网关 `10.0.0.200` （旁路由） dns 服务器地址 `10.0.0.200` （旁路由），访问 `baidu.com` 报错 `DNS_ORIBE_FINSHED_BAD_CONFIG` ，访问 `220.181.112.244` （百度数字 ip）可正常访问，初步判定旁路由 dns 服务器存在问题（本人未在旁路由中自行搭建过任何 dns 服务器）

修改测试机 DNS 为主路由 `10.0.0.101` ，访问 `baidu.com` `220.181.112.244` 均正常，请求局域网其他机器，发现 IP 是 `10.0.0.85` （测试机 ip ，非旁路由 ip）

测试过程中 clash-meta 全程未发现任何有关日志，仅有 socks5 连接时才出现日志
