### ISSUE TITLE
[咨询] 关于使用 Meta/Mihomo 内核时 geosite 自动更新的问题

### ISSUE THREAD

**Issue by chshouyu** [juewuy/ShellCrash#651]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

<img width="795" alt="image" src="https://github.com/juewuy/ShellCrash/assets/1304342/23715e9f-f390-4b48-a84c-856e0f424f9e">

官方文档有配置自动更新的选项，但是在 ShellCrash 安装时，推荐的定时任务里没有关于何时自动更新 geosite 的任务

而且我查看了一下 `/tmp/ShellCrash/config.yaml` 里的内容，发现也没有相关的配置

目前的自动任务有：

<img width="271" alt="image" src="https://github.com/juewuy/ShellCrash/assets/1304342/452511c7-838a-4a41-8896-7dc6c35da14e">

想问一下：

1. ShellCrash 有没有接管自动更新 GEO 相关的配置？
2. 我需不需要自己添加一个 `10 自动更新数据库文件` 的任务？
3. 假如需要添加一个 `10 自动更新数据库文件` 的任务，还需不需要添加一个 `3 重启clash服务` 任务以使新的数据库文件生效？

感谢作者带来这么棒的项目😁

**Comment by juewuy** [comment]
没有
需要
需要

**Comment by chshouyu** [comment]
感谢解答~
如果我将规则换成 RULE-SET 形式，它自带了一个 `interval`，是不是就不需要操心这么多了？

**Comment by juewuy** [comment]
@chshouyu meta应该支持内核级更新geo数据库

**Comment by chshouyu** [comment]
那 ShellCrash 在启动时自动下载的 `GeoSite.dat` 是应用在哪方面了呢？

**Comment by juewuy** [comment]
@chshouyu 内核自动更新需要额外设置配置文件

**Comment by chshouyu** [comment]
我试过了，参考这里 [metacubex](https://wiki.metacubex.one/config/general/#geoip)，我在自己的 config.yaml 里加了一段：

```yaml
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat'
  geosite: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat'
  mmdb: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb'
  asn: 'https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb'
```

上传到 /tmp/，加载重启 ShellCrash 之后，再查看 /tmp/ShellCrash/config.yaml，发现这一段消失了
