### ISSUE TITLE
[Bug] hosts劫持不生效？

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#684]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如图，DNS解析结果并不是hosts中配置的：

![Screenshot_2024-06-24-20-48-38-378_com sonelli juicessh](https://github.com/juewuy/ShellCrash/assets/53206264/9083864f-1bc6-46e7-9eca-7965bfb47084)
![Screenshot_2024-06-24-20-48-27-772_com youdao note](https://github.com/juewuy/ShellCrash/assets/53206264/4ca3cf6d-af41-4463-abd5-83f145f2e316)
![Screenshot_2024-06-24-20-50-22-767_com android chrome](https://github.com/juewuy/ShellCrash/assets/53206264/5535fe59-77ad-40d3-bef5-7eb62e6da811)

**Comment by suikastar** [comment]
https://github.com/MetaCubeX/metacubexd/issues/785

**Comment by juewuy** [comment]
@suikastar 请先确认DNS是否被内核正确劫持到了

**Comment by suikastar** [comment]
@juewuy 十分钟前试了一下，路由器和电脑发起dns解析，结果都是hosts指定的，不确定是谁的bug，但肯定不是脚本的

**Comment by happyeddie** [comment]
同样的问题，排查了一下，发现是生成的 ShellCrash/config.yaml （这个文件是不是最终运行的配置文件）中：
1. 如果开始了 2-2-4-5 / hosts优化，config.yaml 中的内容会被替换成固定的配置，看上去都是和 NTP 相关
2. 如果关闭了 2-2-4-5 / hosts优化，config.yaml 中 hosts 的内容为空
无论上面那种情况，都没有使用指定的 hosts 内容
不知道是内核的问题，还是 ShellCrash 的问题？ @juewuy jue thx

**Comment by juewuy** [comment]
@happyeddie 脚本机制是启动时自动加载/etc/hosts文件并写入到配置中（也可能是其他hosts文件），如果你的hosts没用写入系统的相关文件就不会加载
不支持在config.yaml中配置任何参数，config.yaml中只会取节点和规则

**Comment by suikastar** [comment]
@happyeddie 你跟我说的不是同一件事，你可以试试自定义user.yaml看看，这是我的
```
tcp-concurrent: true
dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:1053
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.*
  default-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://223.6.6.6/dns-query
    - https://120.53.53.53/dns-query
  nameserver:
    - https://1.1.1.1/dns-query#🚀 节点选择
    - https://8.8.8.8/dns-query#🚀 节点选择
    - https://1.0.0.1/dns-query#🚀 节点选择
    - https://8.8.4.4/dns-query#🚀 节点选择
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://223.6.6.6/dns-query
    - https://120.53.53.53/dns-query
  nameserver-policy:
    rule-set:ads: rcode://success
    rule-set:microsoft-cn,apple-cn,google-cn,games-cn,cn,private:
      - https://223.5.5.5/dns-query
      - https://1.12.12.12/dns-query
      - https://223.6.6.6/dns-query
      - https://120.53.53.53/dns-query
    rule-set:proxy:
      - https://1.1.1.1/dns-query#🚀 节点选择
      - https://8.8.8.8/dns-query#🚀 节点选择
      - https://1.0.0.1/dns-query#🚀 节点选择
      - https://8.8.4.4/dns-query#🚀 节点选择
```

**Comment by happyeddie** [comment]
我也是在自定义 yaml 文件中，参照文档格式，写了一段自定义 hosts，类似下面的格式:

```yaml
hosts:
  '*.clash.dev': 127.0.0.1
  'alpha.clash.dev': '::1'
  test.com: [1.1.1.1, 2.2.2.2]
  baidu.com: google.com
  home.lan
```

但是这段自定义 yaml 并没有出现在 ShellCrash/config.yaml 中，这是符合预期的是么？
