### ISSUE TITLE
[Bug] 1.9.1rc9 虚拟机容器 网络劫持无效

### ISSUE THREAD

**Issue by dr-forget** [juewuy/ShellCrash#808]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

已经开启虚拟器容器的网段劫持 但是仍无效
<img width="639" alt="image" src="https://github.com/user-attachments/assets/a81c34d1-0b3f-4e7b-8174-127f9fe3536b">
<img width="716" alt="image" src="https://github.com/user-attachments/assets/1b057570-d9da-4273-a104-5d7e5e952b6b">

容器内部测试：

<img width="655" alt="image" src="https://github.com/user-attachments/assets/5436832f-c551-4a7b-a08b-032a8e39ddc0">

**Comment by juewuy** [comment]
DNS应该已经劫持成功了，请结合网页面板排查节点或规则

**Comment by iamobj** [comment]
我也遇到这个问题，我通过 6-6-5 自定义高级功能，改写了 dns 配置就可以了
```
dns:
  enable: true
  listen: 0.0.0.0:1053
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  nameserver:
  - tls://8.8.4.4
  - tls://208.67.222.222
  ipv6: false
  enhanced-mode: redir-host
```
