### ISSUE TITLE
[Bug] v1.9.2alpha4在使用 mihomo 并开启了 mix 模式时不能通过自定义高级功能添加rule-providers

### ISSUE THREAD

**Issue by expliyh** [juewuy/ShellCrash#839]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

错误提示：error msg="yaml: unmarshal errors:
  line 10447: mapping key \"rule-providers\" already defined at line 165"

推测是由于 mix 模式向配置文件中插入了一个 rule-providers 导致自定义的 rule-providers 变成了重复的 key，将模式改为fakeip后就不提示了。

**Comment by juewuy** [comment]
@expliyh 在哪里自定义的？user.yaml还是others.yaml?

**Comment by expliyh** [comment]
others.yaml

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by juewuy** [comment]
@expliyh OK

**Comment by juewuy** [comment]
使用了自定义rule-providers的用户，如需启用mix模式，需要手动添加如下规则集（二选一）
使用本地规则集：
```
cn:
    type: file
    behavior: domain
    format: mrs
    path: ./ruleset/cn.mrs
```
使用在线规则集：
```
cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs"
    interval: 600
```
