### ISSUE TITLE
无论是自带的订阅转换还是使用proxy-providers自己写配置文件，hysteria2节点均被过滤没有显示

### ISSUE THREAD

**Issue by chuwza** [juewuy/ShellCrash#887]
大佬好，我的机场包含有hysteria2节点，ShellCrash 1.9.1，Meta内核 1.18.7

我先通过6-1的在线subconverter服务输入订阅链接、生成配置文件。然后打开生成的配置文件，发现里面不存在hysteria2节点（这说明自带的subconverter在线服务不支持hysteria2）；

然后我试着自己手搓配置文件
```
proxy-providers:
 机场1: 
    type: http
    path: ./proxy/1.yaml
    url: "隐去" 
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
      
  - name: "Global"
    type: select
    use: 
      - 机场1
      - 机场2
```
上传到ShellCrash，无论如何都无法让机场的hysteria2节点显示出来，总是显示被过滤

<img width="188" alt="Image" src="https://github.com/user-attachments/assets/eed30d9b-4a44-4ebe-a8ab-6b2a042877b8" />

其实6-1只是测试，我真正需求是想知道手搓配置文件支持hysteria2应该怎么写，因为我有多个机场

（目前我强行让hysteria2节点显示出来的方法是：先使用Windows上的Clash Verge导入订阅链接，将导入后生成的配置文件改名并上传到ShellCrash目录，从而让hysteria2节点显示出来了，但这只是临时的办法，用来证明ShellCrash支持hysteria2罢了）

<img width="188" alt="Image" src="https://github.com/user-attachments/assets/fbc42dd9-5b61-4fb2-8b6e-bc5f19e8672c" />
