### ISSUE TITLE
[Bug] 配置文件不支持 YAML Alias 语法

### ISSUE THREAD

**Issue by Dustella** [juewuy/ShellCrash#923]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [x]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [x]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

使用一个带有 yaml alias 语法的文件，在 shellcrash 修饰配置文件的时候似乎会把 alias 给干掉，让它找不到引用。

样例配置文件：

https://paste.sh/H7WDICS7#LIcvJfsJbSkPiGaxjxuu83R2

其中 

```yaml
p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - 1.主要地址
    - 2.备用地址

proxy-providers:
  1.主要地址:
    <<: *p
    url: ""
    path: ./proxy_providers/subscribe1.yaml
    
  2.备用地址:
    <<: *p
    url: ""
    path: ./proxy_providers/subscribe2.yaml
```

中，前面的 alias 定义会被 shellcrash 在预处理的时候丢掉。

bug log：

```
9]: 4月 04 15:34:55 mercury start.sh[44049]: 4月 04 15:33:35 mercury start.sh[42391]: 4月 04 15:33:25 mercury CrashCore[42390]: time="2025-04-04T15:33:25.525178672+08:00" level=fatal msg="Parse config error: yaml: unknown anchor 'u' referenced"
4月 04 16:23:21 mercury start.sh[62037]: 4月 04 15:52:00 mercury start.sh[49385]: 4月 04 15:37:53 mercury start.sh[45749]: 4月 04 15:34:55 mercury start.sh[44049]: 4月 04 15:34:45 mercury start.sh[43878]: error msg="yaml: unknown anchor 'u' referenced"
```
